### ISSUE TITLE
Initial draft and planning

### ISSUE THREAD

**Issue by AGraber** [AGraber/PawnPlusCMD#1]
So, earlier today I finished a very basic working prototype of a new command processor that takes advantage of PawnPlus's features to make commands.

## What's done until now
Right now, it's pretty much barebones but it works and has a feature that no other command processor has:
- Commands using the classic `CMD:` macro are implemented.
- Commands are parsed for parameters and tags, this means you can do `CMD:setmyhealth(playerid, Float:health)` without having to use anything like `sscanf` or `strtok`. This is powered by the sscanf plugin.
- That the old `params[]` parameter works is merely a side effect from the automatic parsing, which recognizes that this is a string. It gets needlessly parsed by sscanf though, so I'll optimize it later to pass single strings as-is. It also incorrectly treats a command without parameters and fails "parsing" it.
- Commands can have flags, using syntax borrowed from the existing SmartCMD.
- Commands can be disabled
- Command aliases without any overhead. Unlike some other command processors, aliases here refer to the same command array structure (containing flags, disabled state and etc.) that was created by the main command and also used by any other aliases, so disabling the main command will also disable any aliases it has. I implemented the SmartCMD and Pawn.CMD macros, `ALT:alias = CMD:original` and `alias:original("alias", "anotheralias)` respectively
- `forward OnPlayerCommandReceived(playerid, cmd[], params[], flags);` and `forward OnPlayerCommandPerformed(playerid, cmd[], params[], flags, E_COMMAND_RESULT:result, return_value);`

## What's planned
- A `Player:` tag for commands that doesn't interfere with the tag. The only way I've come up for doing this without messing with the parameter's tag is by doing a "fake" variable: one for detecting the tag, the other one for actually receiving the variable.
- Add automatic usage messages, using debug info to get the parameters names and display them. For example, if you try to use `CMD:setmyhealth(playerid, Float:health)` without the correct arguments, you will get `USAGE: /setmyhealth [armhealthour]`
- Add overrides for these messages. Let's say you've got some embarrasing argument name like `playa` and you don't want to bother changing it, but you don't want your players seeing it either. I'm thinking something like this: `cmdusage:setmyhealth("message here");` but I'd welcome other syntaxes as well.
- Add proper backwards compatibility with single string parameter CMDs
- Build the expression by using the expression natives instead of building a string and then parsing it.

## About the callbacks and other stuff that's subject to change
So, I've added flags as they are useful to "group" commands with a flag to then check the on the OnPlayerCommandReceived and OnPlayerCommandPerformed callbacks. Regarding these, I want some feedback since different command processors have different implementations and checks regarding the return values of these.

Currently, it behaves like this:

1. OnPlayerCommandText gets called
2. OnPlayerCommandReceived gets called, even if the command doesn't exist. Flags are 0 when the command doesn't exist (but not when it's disabled). 3 and 4 are ignored when the command doesn't exist. If you return 0 here, the OnPlayerCommandText callback returns with 1 (no "SERVER:..." message), and none of the following gets executed.
3. If the command exists and it's not disabled, it gets parsed by the cached expression using sscanf.
4. If the sscanf call return success, the command gets called.
5. The value of OnPlayerCommandPerformed gets returned to the OnPlayerCommandText callback. Returning 0 here will do `SERVER: Unknown Command`.

Also, this name is not 100% final, if someone comes up with something better I'd change it to that.

Any thoughts? Something I should change?

I'll leave this prototype here too, in case anyone wants to look my messy WIP code:
https://gist.github.com/AGraber/43afda5d6667094d164cddfd1e96af93

**Comment by kristoisberg** [comment]
you sexy man

**Comment by spacemud** [comment]
I'd like a way to be able to iterate through commands (globally but also depending on flags used) and their parameters, say for formatting dialogs or other command lists.

**Comment by AGraber** [comment]
Create other issues for what you want to request.
